POST http://localhost:3003/api/users/
Content-Type: application/json

{
    "username": "robert",
    "name": "Roberto",
    "password": "sophiasamuel",
    "blogs": []
}
###
POST http://localhost:3003/api/users/
Content-Type: application/json

{
    "username": "fedpre",
    "name": "Federico",
    "password": "sophiasamuel",
    "blogs": []
}
###
POST http://localhost:3003/api/users/
Content-Type: application/json

{
    "name": "luca",
    "password": "fdsfds",
    "blogs": []
}
### 
POST http://localhost:3003/api/users/
Content-Type: application/json

{
    "username": "cri",
    "name": "Cristina",
    "blogs": []
}
###
POST http://localhost:3003/api/users/
Content-Type: application/json

{
    "username": "re",
    "name": "Reginald",
    "password": "dfsf",
    "blogs": []
}
###
POST http://localhost:3003/api/users/
Content-Type: application/json

{
    "username": "reginald",
    "name": "Reginald",
    "password": "d",
    "blogs": []
}
###

POST http://localhost:3003/api/users/
Content-Type: application/json

{
    "username": "bobby",
    "name": "Alberto",
    "password": "sophiasamuel",
    "blogs": []
}
###