POST http://localhost:3003/api/blogs
Content-Type: application/json

{
    "title": "Test 1",
    "author": "Federico Pregnolato",
    "url": "https://twitter.com",
    "likes": 50,
    "userId": "61fea7768bb7f71687f028b5"
}
###
POST http://localhost:3003/api/blogs
Content-Type: application/json

{
    "title": "Test 2",
    "author": "Federico Pregnolato",
    "url": "https://twitter.com",
    "likes": 15,
    "userId": "61fea7768bb7f71687f028b5"
}
###

POST http://localhost:3003/api/blogs
Content-Type: application/json

{
    "title": "Test 5",
    "author": "Federico Pregnolato",
    "url": "https://twitter.com",
    "likes": 67,
    "userId": "6202a9036c4dfc12345b9ebb"
}
###

POST http://localhost:3003/api/blogs
Content-Type: application/json

{
    "title": "Test 6",
    "author": "Federico Pregnolato",
    "url": "https://twitter.com",
    "likes": 70
}
###

POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImZlZHByZSIsImlkIjoiNjFmZWE3NzY4YmI3ZjcxNjg3ZjAyOGI1IiwiaWF0IjoxNjQ0NDg1NjY5fQ.ftEFBm04zniIHIDv998z5KX4XPmpw-Izj64J_Pnhs94

{
    "title": "Test token authentication",
    "author": "Federico Pregnolato The Best",
    "url": "https://fedpregnolato.io",
    "likes": 170
}

###

POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImZlZHByZSIsImlkIjoiNjFmZWE3NzY4YmI3ZjcxNjg3ZjAyOGI1IiwiaWF0IjoxNjQ0NDg5NTY3fQ.PDB-_I4olL0kVrdH1YjgBBpdXD0MWpuu0GsUwLBzgu0

{
    "title": "Test token authentication middleware 2",
    "author": "Fede",
    "url": "https://fedpregnolato.io",
    "likes": 15
}